name: 'Lint checking for typescript'
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: 'Checking Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Test
        run: pnpm lint
